services:
  network-multitool:
    image: ericwastakenondocker/network-multitool
    container_name: network-multitool
    hostname: network-multitool
    restart: no
    network_mode: "host"
    environment:
      - HTTP_PORT=8080
      - HTTPS_PORT=1443
    volumes:
      - ./host-volume:/root/host-volume
