#!/bin/bash

# set a variable with the path of where the script file is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# detect if the compose is running and start if not
if [ ! "$(docker ps -q -f name=network-multitool)" ]; then
    echo "Starting the network-multitool container..."
    cd "$SCRIPT_DIR/.." || exit
    # start the compose
    docker compose up -d
fi

# Exec a command in the container (can receive pipe input)
docker exec -i network-multitool "$@"